name: Build and Deploy to Azure

env:
  AZURE_CONTAINER_REGISTRY_NAME: "sky0327"
  AZURE_CONTAINER_REGISTRY: "sky0327.azurecr.io"
  CONTAINER_NAME: "hello-world"
  RESOURCE_GROUP: "github-actions-demo"
  CLUSTER_NAME: "sky-k8-demo"
  DEPLOYMENT_MANIFEST_PATH: "kubernetes"

on:
  push:
    branches: [ "master"]
  workflow_dispatch:  #manually trigger

permissions:
  contents: read

jobs:
  buildImages:
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout
      uses: actions/checkout@v4.1.2

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3.2.0

    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        # Container registry username
        username: ${{env.AZURE_CONTAINER_REGISTRY_NAME}} 
        # Container registry password
        password: ${{secrets.AZURE_CONTAINER_REGISTRY_PASSWORD}}
        # Container registry server url
        login-server: ${{env.AZURE_CONTAINER_REGISTRY}}
              
    - name: Build and push Docker images
      uses: docker/build-push-action@v5.3.0
      with:
        push: true
        tags: ${{env.AZURE_CONTAINER_REGISTRY}}/${{env.CONTAINER_NAME}}:${{github.sha}}
        file: ./Dockerfile
  deploy:
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      id-token: write

    environment: Production
    needs: [buildImage]

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2

      - name: Azure Login
        uses: Azure/login@v2.0.0
        with:
          client-id: ${{secrets.AZURE_CLIENT_ID}} 
          tenant-id: ${{secrets.AZURE_TENANT_ID}}
          subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}}

      - name: Setup kubelogin
        uses: Azure/use-kubelogin@v1                
      
      - name: Azure Kubernetes set context
        uses: Azure/aks-set-context@v3
        with:
          # Resource Group Name
          resource-group: ${{env.RESOURCE_GROUP}}
          # AKS Cluster Name
          cluster-name: ${{env.CLUSTER_NAME}}
          admin: 'false'
          # Enables kubelogin for non-admin user scenario. Values: true or false
          use-kubelogin: 'true' # optional
                
      - name: envsubst-action
        uses: danielr1996/envsubst-action@1.1.0
        env:
          MONGODB_URI: ${{secrets.MONGODB_URI}}
          AZURE_CONTAINER_REGISTRY_NAME: ${{env.AZURE_CONTAINER_REGISTRY_NAME}}
          AZURE_CONTAINER_REGISTRY: ${{env.AZURE_CONTAINER_REGISTRY}}
        with:
          input: 
            ${{env.DEPLOYMENT_MANIFEST_PATH}}/hello-world-deployment.yaml
          output: 
            hello-world-deployment.yaml
      - name: Deploys application
        uses: Azure/k8s-deploy@v4
        with:
          action: deploy
          manifests: |
            hello-world-deployment.yaml
            ${{env.DEPLOYMENT_MANIFEST_PATH}}/hello-world-service.yaml
          iamges: |
            ${{env.AZURE_CONTAINER_REGISTRY}}/${{env.CONTAINER_NAME}}:${{github.sha}}

            
      
      
